# Generated by Django 2.2 on 2019-11-19 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '10-评论表', 'verbose_name_plural': '10-评论表'},
        ),
        migrations.AddField(
            model_name='comment',
            name='replier',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='回复人'),
        ),
        migrations.AddField(
            model_name='comment',
            name='reply',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='回复内容'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='评论时间'),
        ),
        migrations.AlterField(
            model_name='pricepolicy',
            name='promotion_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='comment',
            table='10-评论表',
        ),
    ]
