# Generated by Django 2.2 on 2019-11-19 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0002_auto_20191119_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='head_img',
            field=models.CharField(default='/static/avatar/default.png', max_length=256, verbose_name='个人头像'),
        ),
        migrations.AddField(
            model_name='account',
            name='pwd',
            field=models.CharField(default='', max_length=128, verbose_name='密码'),
            preserve_default=False,
        ),
    ]
