# Generated by Django 2.2 on 2019-11-19 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0003_auto_20191119_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='account',
            field=models.ForeignKey(on_delete=True, related_name='accounts', to='Course.Account', verbose_name='会员名'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='replier',
            field=models.ForeignKey(blank=True, null=True, on_delete=True, to='Course.Account', verbose_name='回复人'),
        ),
    ]
